# -*- coding: utf-8 -*-
"""Chess-Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H2HTsJGGYT0L7bpZiD-OagSHTMkn9cdU

**LIBRARY**
"""

import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

"""**TOP 50 PLAYERS**"""

dic = {'carlsen':'1503014','ding':'8603677','nepo':'4168119',\
       'firouja':'12573981','so':'5202213','nakamura':'2016192',\
       'giri':'24116068','caruana':'2020009','anand':'5000017',\
       'aronian':'13300474','rapport':'738590','perez':'3503240',\
       'mamedyarov':'13401319','mvl':'623539','karjakin':'14109603',\
       'radjabov':'13400924','grischuk':'4126025',\
       'gukesh':'46616543','duda':'1170546','andreikin':'4158814','erigaisi':'35009192',\
       'liem':'12401137','topalov':'2900084','yi':'8603405','nikita':'4152956',\
       'hao':'8602883','parham':'12539929','yangyi':'8603820',\
       'harikrishna':'5007003','pons':'2205530','abdusattorov':'14204118',\
       'shankland':'2004887','sargissian':'13300881',\
       'vidit':'5029465','sjugirov':'4189302','dubov':'24126055','deac':'1226380','artemiev':'24101605',\
       'keymer':'12940690','niemann':'2093596','bu':'8601445','eljanov':'14102951',\
       'tomashevsky':'4147235','foreest':'1039784',\
       'wojtaszek':'1118358','alekseenko':'4135539','robson':'2023970',\
       'xiong':'2047640','cheparinov':'2905540','adams':'400041'}

"""**DATASET WITH ALL PLAYERS DATA**"""

fidedf = pd.DataFrame()
appended_data = []

for key, value in dic.items():
  url = f'https://ratings.fide.com/profile/{value}'
  
  #exceptions created to few players
  exceptions1 = ['carlsen','nakamura','caruana','nepo','so','aronian','perez',\
                 'mamedyarov','mvl','karjakin','radjabov','grischuk','topalov',\
                 'hao','harikrishna','sargissian','sjugirov','bu','eljanov','tomashevsky',\
                 'wojtaszek','adams']
  exceptions2 = ['anand','yi','cheparinov']
  exceptions3 = ['andreikin','nikita']
  exceptions4 = ['alekseenko']

  if key in exceptions1 :
    temp_df = pd.read_html(url)[5]
  elif key in exceptions2 :
    temp_df = pd.read_html(url)[7]
  elif key in exceptions3 :
    temp_df = pd.read_html(url)[2]
  elif key in exceptions4 :
    temp_df = pd.read_html(url)[3]
  else:
    temp_df = pd.read_html(url)[6]

  #only desired columns
  temp_df = temp_df.filter(['Period','GMS','RTNG'], axis=1)

  #add col Name
  temp_df['Name']= key
  
  #add col key
  temp_df['FideID']= value   
      
  #invert  
  temp_df = temp_df.sort_index(ascending=False)
  temp_df.insert(0, 'time_playing', range(1, 1 + len(temp_df)))

  #RTNG diff
  temp_df['rtng_diff'] = temp_df['RTNG'].diff()
  temp_df['rtng_diff'] = temp_df['rtng_diff'].fillna(0)
    
  #GMS/RTNG
  temp_df["ratio"] = temp_df["GMS"]/temp_df["RTNG"]

  #append
  appended_data.append(temp_df)

#create dataframe with all players
fidedf = pd.concat(appended_data)

#convert Period
fidedf['Period'] = pd.to_datetime(fidedf['Period'])

#Put RTNG in the end of dataframe
fidedf['Rating'] = fidedf['RTNG'] * 1
fidedf.drop(['RTNG'], axis=1, inplace=True)

fidedf.count()

from google.colab import drive
drive.mount('drive')

fidedf.to_csv('fidedfv5.csv')
!cp fidedfv5.csv "drive/My Drive/"
